development:
 secret_key_base: a8d5a5706cf53...
 facebook_app_id: <%= ENV["381156869034730"] %>
 facebook_app_secret: <%= ENV["af04d1e74eaca77242ad9b47edcf099d"] %>
test:
 secret_key_base: 432cb5d950462...
 facebook_app_id: <%= ENV["381156869034730] %>
 facebook_app_secret: <%= ENV["af04d1e74eaca77242ad9b47edcf099d"] %>
production:
 secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
 facebook_app_id: <%= ENV["381156869034730"] %>
 facebook_app_secret: <%= ENV["af04d1e74eaca77242ad9b47edcf099d"] %>
